name: Build Frontend

on:
  push:
    branches: [main, tp2]
  pull_request:
    branches: [main, tp2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t task-manager-frontend ./frontend
      - name: Scan frontend image
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasecurity/trivy:latest image \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            --format table \
            task-manager-frontend
