name: Lint Dockerfiles

on:
  push:
    branches: [main, tp2]
  pull_request:
    branches: [main, tp2]

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint backend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: backend/Dockerfile
          failure-threshold: warning
          format: tty

      - name: Lint frontend Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: frontend/Dockerfile
          failure-threshold: warning
          format: tty
