name: pre-commit
on:
  push:
    branches: [tp2]
  pull_request:
    branches: [tp2]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Récupère le code source du repo dans la VM
      - uses: actions/checkout@v4

      # Installe Python 3.12
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Idem que l'éxecution local
      - uses: pre-commit/action@v3.0.1